# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy JAR to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  NODE_VERSION: 16.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.JAVA_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Packages
        run:  npm install

      - name: Build and minify project
        run: npm run build

      - name: Zip artifact for Deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: yelpcamp-app
          path: release.zip

  deploy:
    name: Deploy to Azure Cloud
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from Build job
        uses: actions/download-artifact@v2
        with:
          name: yelpcamp-app

      - name: Unzip artifact for Deployment
        run: unzip release.zip

      - name: Deploy to Azure Webapp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'milans-yelpcamp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_YELPCAMP }}
          package: .